# project name
spring:
  application:
    name: CampingNavi
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: '오라클 드라이버 주소'
    username: '오라클 사용자 아이디'
    password: '비밀번호'
  jpa:
    database: oracle
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        format_sql: true
  #Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: '전송자용 이메일'
    password: '시크릿 패스워드(구글 어플리케이션 등록 후 발급받은 키)'
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  # ststic파일 개발시 서버를 재시작하지않고 수정한 내용이 반영되도록 추가된 툴
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/chatdb

  # SNS 로그인
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: '구글 어플리케이션 등록후 발급받은 아이디 번호'
            client-secret: '발급받은 시크릿 키'
            scope:
              - email
              - profile
          kakao:
            client-id: '카카오 어플리케이션 등록후 발급받은 아이디 번호'
            client-secret: '발급받은 시크릿 키'
            scope:
              - account_email
              - profile_nickname
              - profile_image
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: client_secret_post
          naver:
            client-id: '네이버 어플리케이션 등록후 발급받은 아이디 번호'
            client-secret: '발급받은 시크릿 키'
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          facebook:
            client-id: '페이스북 어플리케이션 등록후 발급받은 아이디 번호'
            client-secret: '발급받은 시크릿 키'
            scope:
              - email
              - public_profile

        provider:
          kakao:
            authorization-uri: '인가 url'
            token-uri: '토큰 url'
            user-info-uri: 'api url'
            user-name-attribute: id
          naver:
            authorization-uri: '인가 url'
            token-uri: '토큰 url'
            user-info-uri: 'api url'
            user-name-attribute: response
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
# server port
server:
  port: 8080