# project name
spring:
  application:
    name: CampingNavi
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: camp_user
    password: ora123
  jpa:
    database: oracle
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        format_sql: true
  # ststic파일 개발시 서버를 재시작하지않고 수정한 내용이 반영되도록 추가된 툴
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/chatdb

# server port
server:
  port: 8080