# project name
spring:
  application:
    name: CampingNavi
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: camp_user
    password: ora123
  jpa:
    database: oracle
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        format_sql: true
  #Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: tksdl1561@gmail.com
    password: jyba sage qokd lehh
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  # ststic파일 개발시 서버를 재시작하지않고 수정한 내용이 반영되도록 추가된 툴
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/chatdb

  # SNS 로그인
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 39193396108-o1mgb8rf2260m52p8q3qbnd3d5p2i0ut.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

# server port
server:
  port: 8080